[package]
name = "untitled12345"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
non-empty-vec = "0.2.3"
pprof = { version = "0.9.1", features = ["flamegraph", "protobuf"] }
